# Generated by Django 5.0.6 on 2024-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_adminsuper'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
