# Generated by Django 5.0.6 on 2024-05-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0005_updateduser_alter_adminsuper_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateduser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
