# Generated by Django 5.0.6 on 2024-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0006_alter_updateduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateduser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
